// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file common.proto (package shw, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SA3NodyJeCg5Db21tb25SZXNwb25zZRIKCgJvaxgBIAEoCBISCgpzdGF0dXNDb2RlGAIgASgDEg8KB21lc3NhZ2UYAyABKAkSGwoGcmVzdWx0GAQgASgLMgsuc2h3LlJlc3VsdCIyCghVc2VySW5mbxIKCgJpZBgBIAEoBBIMCgRuYW1lGAIgASgJEgwKBHJvbGUYAyABKAkiFAoGUmVzdWx0EgoKAmlkGAEgASgEQhJaEHNod2dycGMvcGtnL2dycGNiBnByb3RvMw");

/**
 * @generated from message shw.CommonResponse
 */
export type CommonResponse = Message<"shw.CommonResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * @generated from field: int64 statusCode = 2;
   */
  statusCode: bigint;

  /**
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * @generated from field: shw.Result result = 4;
   */
  result?: Result;
};

/**
 * Describes the message shw.CommonResponse.
 * Use `create(CommonResponseSchema)` to create a new message.
 */
export const CommonResponseSchema: GenMessage<CommonResponse> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * @generated from message shw.UserInfo
 */
export type UserInfo = Message<"shw.UserInfo"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string role = 3;
   */
  role: string;
};

/**
 * Describes the message shw.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema: GenMessage<UserInfo> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * @generated from message shw.Result
 */
export type Result = Message<"shw.Result"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message shw.Result.
 * Use `create(ResultSchema)` to create a new message.
 */
export const ResultSchema: GenMessage<Result> = /*@__PURE__*/
  messageDesc(file_common, 2);

