// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file family.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddFamilyMemberRequest, Family, FamilyRequest, FamilyResponse } from "./family_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { CommonResponse } from "./common_pb.js";

/**
 * @generated from service shw.FamilyService
 */
export const FamilyService = {
  typeName: "shw.FamilyService",
  methods: {
    /**
     * @generated from rpc shw.FamilyService.GetFamily
     */
    getFamily: {
      name: "GetFamily",
      I: FamilyRequest,
      O: FamilyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.CreateFamily
     */
    createFamily: {
      name: "CreateFamily",
      I: Family,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.UpdateFamily
     */
    updateFamily: {
      name: "UpdateFamily",
      I: Family,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.DeleteFamily
     */
    deleteFamily: {
      name: "DeleteFamily",
      I: Family,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.AddFamilyMember
     */
    addFamilyMember: {
      name: "AddFamilyMember",
      I: AddFamilyMemberRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

