// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file family.proto (package shw, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { CommonResponseSchema, UserInfo } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file family.proto.
 */
export const file_family: GenFile = /*@__PURE__*/
  fileDesc("CgxmYW1pbHkucHJvdG8SA3NodyIhCg1GYW1pbHlSZXF1ZXN0EhAKCGZhbWlseUlkGAEgASgEIi8KG0ZhbWlseUhvdXNld29ya1BvaW50UmVxdWVzdBIQCghmYW1pbHlJZBgCIAEoBCJRChxGYW1pbHlIb3VzZXdvcmtQb2ludFJlc3BvbnNlEjEKDmhvdXNld29ya1BvaW50GAEgAygLMhkuc2h3LkZhbWlseUhvdXNld29ya1BvaW50InQKFEZhbWlseUhvdXNld29ya1BvaW50EgoKAmlkGAEgASgEEhsKBHVzZXIYAiABKAsyDS5zaHcuVXNlckluZm8SDQoFcG9pbnQYBCABKAMSEQoJY3JlYXRlZEF0GAUgASgDEhEKCXVwZGF0ZWRBdBgGIAEoAyJHChZBZGRGYW1pbHlNZW1iZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkSDQoFZW1haWwYAiABKAkSEAoIZmFtaWx5SWQYAyABKAQiLQoORmFtaWx5UmVzcG9uc2USGwoGZmFtaWx5GAEgASgLMgsuc2h3LkZhbWlseSJZCgZGYW1pbHkSCgoCaWQYASABKAQSGwoEdXNlchgCIAMoCzINLnNody5Vc2VySW5mbxIMCgRuYW1lGAMgASgJEhgKEHBvaW50UGVyV29ya1RpbWUYBCABKAkiKQoRRmFtaWx5Um9sZVJlcXVlc3QSFAoMZmFtaWx5Um9sZUlkGAEgASgEIk0KCkZhbWlseVJvbGUSCgoCaWQYASABKAQSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIQCghmYW1pbHlJZBgEIAEoBCI5ChJGYW1pbHlSb2xlUmVzcG9uc2USIwoKZmFtaWx5Um9sZRgBIAMoCzIPLnNody5GYW1pbHlSb2xlMqUECg1GYW1pbHlTZXJ2aWNlEjYKCUdldEZhbWlseRISLnNody5GYW1pbHlSZXF1ZXN0GhMuc2h3LkZhbWlseVJlc3BvbnNlIgASMgoMQ3JlYXRlRmFtaWx5Egsuc2h3LkZhbWlseRoTLnNody5Db21tb25SZXNwb25zZSIAEjIKDFVwZGF0ZUZhbWlseRILLnNody5GYW1pbHkaEy5zaHcuQ29tbW9uUmVzcG9uc2UiABIyCgxEZWxldGVGYW1pbHkSCy5zaHcuRmFtaWx5GhMuc2h3LkNvbW1vblJlc3BvbnNlIgASRQoPQWRkRmFtaWx5TWVtYmVyEhsuc2h3LkFkZEZhbWlseU1lbWJlclJlcXVlc3QaEy5zaHcuQ29tbW9uUmVzcG9uc2UiABI+Cg1HZXRGYW1pbHlSb2xlEhIuc2h3LkZhbWlseVJlcXVlc3QaFy5zaHcuRmFtaWx5Um9sZVJlc3BvbnNlIgASOgoQQ3JlYXRlRmFtaWx5Um9sZRIPLnNody5GYW1pbHlSb2xlGhMuc2h3LkNvbW1vblJlc3BvbnNlIgASOgoQVXBkYXRlRmFtaWx5Um9sZRIPLnNody5GYW1pbHlSb2xlGhMuc2h3LkNvbW1vblJlc3BvbnNlIgASQQoQRGVsZXRlRmFtaWx5Um9sZRIWLnNody5GYW1pbHlSb2xlUmVxdWVzdBoTLnNody5Db21tb25SZXNwb25zZSIAQhJaEHNod2dycGMvcGtnL2dycGNiBnByb3RvMw", [file_common]);

/**
 * @generated from message shw.FamilyRequest
 */
export type FamilyRequest = Message<"shw.FamilyRequest"> & {
  /**
   * @generated from field: uint64 familyId = 1;
   */
  familyId: bigint;
};

/**
 * Describes the message shw.FamilyRequest.
 * Use `create(FamilyRequestSchema)` to create a new message.
 */
export const FamilyRequestSchema: GenMessage<FamilyRequest> = /*@__PURE__*/
  messageDesc(file_family, 0);

/**
 * @generated from message shw.FamilyHouseworkPointRequest
 */
export type FamilyHouseworkPointRequest = Message<"shw.FamilyHouseworkPointRequest"> & {
  /**
   * @generated from field: uint64 familyId = 2;
   */
  familyId: bigint;
};

/**
 * Describes the message shw.FamilyHouseworkPointRequest.
 * Use `create(FamilyHouseworkPointRequestSchema)` to create a new message.
 */
export const FamilyHouseworkPointRequestSchema: GenMessage<FamilyHouseworkPointRequest> = /*@__PURE__*/
  messageDesc(file_family, 1);

/**
 * @generated from message shw.FamilyHouseworkPointResponse
 */
export type FamilyHouseworkPointResponse = Message<"shw.FamilyHouseworkPointResponse"> & {
  /**
   * @generated from field: repeated shw.FamilyHouseworkPoint houseworkPoint = 1;
   */
  houseworkPoint: FamilyHouseworkPoint[];
};

/**
 * Describes the message shw.FamilyHouseworkPointResponse.
 * Use `create(FamilyHouseworkPointResponseSchema)` to create a new message.
 */
export const FamilyHouseworkPointResponseSchema: GenMessage<FamilyHouseworkPointResponse> = /*@__PURE__*/
  messageDesc(file_family, 2);

/**
 * @generated from message shw.FamilyHouseworkPoint
 */
export type FamilyHouseworkPoint = Message<"shw.FamilyHouseworkPoint"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: shw.UserInfo user = 2;
   */
  user?: UserInfo;

  /**
   * @generated from field: int64 point = 4;
   */
  point: bigint;

  /**
   * @generated from field: int64 createdAt = 5;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt: bigint;
};

/**
 * Describes the message shw.FamilyHouseworkPoint.
 * Use `create(FamilyHouseworkPointSchema)` to create a new message.
 */
export const FamilyHouseworkPointSchema: GenMessage<FamilyHouseworkPoint> = /*@__PURE__*/
  messageDesc(file_family, 3);

/**
 * @generated from message shw.AddFamilyMemberRequest
 */
export type AddFamilyMemberRequest = Message<"shw.AddFamilyMemberRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: uint64 familyId = 3;
   */
  familyId: bigint;
};

/**
 * Describes the message shw.AddFamilyMemberRequest.
 * Use `create(AddFamilyMemberRequestSchema)` to create a new message.
 */
export const AddFamilyMemberRequestSchema: GenMessage<AddFamilyMemberRequest> = /*@__PURE__*/
  messageDesc(file_family, 4);

/**
 * @generated from message shw.FamilyResponse
 */
export type FamilyResponse = Message<"shw.FamilyResponse"> & {
  /**
   * @generated from field: shw.Family family = 1;
   */
  family?: Family;
};

/**
 * Describes the message shw.FamilyResponse.
 * Use `create(FamilyResponseSchema)` to create a new message.
 */
export const FamilyResponseSchema: GenMessage<FamilyResponse> = /*@__PURE__*/
  messageDesc(file_family, 5);

/**
 * @generated from message shw.Family
 */
export type Family = Message<"shw.Family"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: repeated shw.UserInfo user = 2;
   */
  user: UserInfo[];

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string pointPerWorkTime = 4;
   */
  pointPerWorkTime: string;
};

/**
 * Describes the message shw.Family.
 * Use `create(FamilySchema)` to create a new message.
 */
export const FamilySchema: GenMessage<Family> = /*@__PURE__*/
  messageDesc(file_family, 6);

/**
 * @generated from message shw.FamilyRoleRequest
 */
export type FamilyRoleRequest = Message<"shw.FamilyRoleRequest"> & {
  /**
   * @generated from field: uint64 familyRoleId = 1;
   */
  familyRoleId: bigint;
};

/**
 * Describes the message shw.FamilyRoleRequest.
 * Use `create(FamilyRoleRequestSchema)` to create a new message.
 */
export const FamilyRoleRequestSchema: GenMessage<FamilyRoleRequest> = /*@__PURE__*/
  messageDesc(file_family, 7);

/**
 * @generated from message shw.FamilyRole
 */
export type FamilyRole = Message<"shw.FamilyRole"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: uint64 familyId = 4;
   */
  familyId: bigint;
};

/**
 * Describes the message shw.FamilyRole.
 * Use `create(FamilyRoleSchema)` to create a new message.
 */
export const FamilyRoleSchema: GenMessage<FamilyRole> = /*@__PURE__*/
  messageDesc(file_family, 8);

/**
 * @generated from message shw.FamilyRoleResponse
 */
export type FamilyRoleResponse = Message<"shw.FamilyRoleResponse"> & {
  /**
   * @generated from field: repeated shw.FamilyRole familyRole = 1;
   */
  familyRole: FamilyRole[];
};

/**
 * Describes the message shw.FamilyRoleResponse.
 * Use `create(FamilyRoleResponseSchema)` to create a new message.
 */
export const FamilyRoleResponseSchema: GenMessage<FamilyRoleResponse> = /*@__PURE__*/
  messageDesc(file_family, 9);

/**
 * @generated from service shw.FamilyService
 */
export const FamilyService: GenService<{
  /**
   * @generated from rpc shw.FamilyService.GetFamily
   */
  getFamily: {
    methodKind: "unary";
    input: typeof FamilyRequestSchema;
    output: typeof FamilyResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.CreateFamily
   */
  createFamily: {
    methodKind: "unary";
    input: typeof FamilySchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.UpdateFamily
   */
  updateFamily: {
    methodKind: "unary";
    input: typeof FamilySchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.DeleteFamily
   */
  deleteFamily: {
    methodKind: "unary";
    input: typeof FamilySchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.AddFamilyMember
   */
  addFamilyMember: {
    methodKind: "unary";
    input: typeof AddFamilyMemberRequestSchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.GetFamilyRole
   */
  getFamilyRole: {
    methodKind: "unary";
    input: typeof FamilyRequestSchema;
    output: typeof FamilyRoleResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.CreateFamilyRole
   */
  createFamilyRole: {
    methodKind: "unary";
    input: typeof FamilyRoleSchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.UpdateFamilyRole
   */
  updateFamilyRole: {
    methodKind: "unary";
    input: typeof FamilyRoleSchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.FamilyService.DeleteFamilyRole
   */
  deleteFamilyRole: {
    methodKind: "unary";
    input: typeof FamilyRoleRequestSchema;
    output: typeof CommonResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_family, 0);

