// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=none"
// @generated from file family.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddFamilyMemberRequest, Family, FamilyRequest, FamilyResponse, FamilyRole, FamilyRoleRequest, FamilyRoleResponse } from "./family_pb";
import { MethodKind } from "@bufbuild/protobuf";
import { CommonResponse } from "./common_pb";

/**
 * @generated from service shw.FamilyService
 */
export const FamilyService = {
  typeName: "shw.FamilyService",
  methods: {
    /**
     * @generated from rpc shw.FamilyService.GetFamily
     */
    getFamily: {
      name: "GetFamily",
      I: FamilyRequest,
      O: FamilyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.CreateFamily
     */
    createFamily: {
      name: "CreateFamily",
      I: Family,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.UpdateFamily
     */
    updateFamily: {
      name: "UpdateFamily",
      I: Family,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.DeleteFamily
     */
    deleteFamily: {
      name: "DeleteFamily",
      I: Family,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.AddFamilyMember
     */
    addFamilyMember: {
      name: "AddFamilyMember",
      I: AddFamilyMemberRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.GetFamilyRole
     */
    getFamilyRole: {
      name: "GetFamilyRole",
      I: FamilyRequest,
      O: FamilyRoleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.CreateFamilyRole
     */
    createFamilyRole: {
      name: "CreateFamilyRole",
      I: FamilyRole,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.UpdateFamilyRole
     */
    updateFamilyRole: {
      name: "UpdateFamilyRole",
      I: FamilyRole,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.FamilyService.DeleteFamilyRole
     */
    deleteFamilyRole: {
      name: "DeleteFamilyRole",
      I: FamilyRoleRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

