// @generated by protoc-gen-es v1.4.1 with parameter "target=ts"
// @generated from file family.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { UserInfo } from "./common_pb.js";

/**
 * @generated from message shw.FamilyRequest
 */
export class FamilyRequest extends Message<FamilyRequest> {
  /**
   * @generated from field: uint64 familyId = 1;
   */
  familyId = protoInt64.zero;

  constructor(data?: PartialMessage<FamilyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyRequest {
    return new FamilyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyRequest {
    return new FamilyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyRequest {
    return new FamilyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyRequest | PlainMessage<FamilyRequest> | undefined, b: FamilyRequest | PlainMessage<FamilyRequest> | undefined): boolean {
    return proto3.util.equals(FamilyRequest, a, b);
  }
}

/**
 * @generated from message shw.FamilyHouseworkPointRequest
 */
export class FamilyHouseworkPointRequest extends Message<FamilyHouseworkPointRequest> {
  /**
   * @generated from field: uint64 familyId = 2;
   */
  familyId = protoInt64.zero;

  constructor(data?: PartialMessage<FamilyHouseworkPointRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyHouseworkPointRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyHouseworkPointRequest {
    return new FamilyHouseworkPointRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyHouseworkPointRequest {
    return new FamilyHouseworkPointRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyHouseworkPointRequest {
    return new FamilyHouseworkPointRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyHouseworkPointRequest | PlainMessage<FamilyHouseworkPointRequest> | undefined, b: FamilyHouseworkPointRequest | PlainMessage<FamilyHouseworkPointRequest> | undefined): boolean {
    return proto3.util.equals(FamilyHouseworkPointRequest, a, b);
  }
}

/**
 * @generated from message shw.FamilyHouseworkPointResponse
 */
export class FamilyHouseworkPointResponse extends Message<FamilyHouseworkPointResponse> {
  /**
   * @generated from field: repeated shw.FamilyHouseworkPoint houseworkPoint = 1;
   */
  houseworkPoint: FamilyHouseworkPoint[] = [];

  constructor(data?: PartialMessage<FamilyHouseworkPointResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyHouseworkPointResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "houseworkPoint", kind: "message", T: FamilyHouseworkPoint, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyHouseworkPointResponse {
    return new FamilyHouseworkPointResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyHouseworkPointResponse {
    return new FamilyHouseworkPointResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyHouseworkPointResponse {
    return new FamilyHouseworkPointResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyHouseworkPointResponse | PlainMessage<FamilyHouseworkPointResponse> | undefined, b: FamilyHouseworkPointResponse | PlainMessage<FamilyHouseworkPointResponse> | undefined): boolean {
    return proto3.util.equals(FamilyHouseworkPointResponse, a, b);
  }
}

/**
 * @generated from message shw.FamilyHouseworkPoint
 */
export class FamilyHouseworkPoint extends Message<FamilyHouseworkPoint> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: shw.UserInfo user = 2;
   */
  user?: UserInfo;

  /**
   * @generated from field: int64 point = 4;
   */
  point = protoInt64.zero;

  /**
   * @generated from field: int64 createdAt = 5;
   */
  createdAt = protoInt64.zero;

  /**
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt = protoInt64.zero;

  constructor(data?: PartialMessage<FamilyHouseworkPoint>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyHouseworkPoint";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "user", kind: "message", T: UserInfo },
    { no: 4, name: "point", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "createdAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "updatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyHouseworkPoint {
    return new FamilyHouseworkPoint().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyHouseworkPoint {
    return new FamilyHouseworkPoint().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyHouseworkPoint {
    return new FamilyHouseworkPoint().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyHouseworkPoint | PlainMessage<FamilyHouseworkPoint> | undefined, b: FamilyHouseworkPoint | PlainMessage<FamilyHouseworkPoint> | undefined): boolean {
    return proto3.util.equals(FamilyHouseworkPoint, a, b);
  }
}

/**
 * @generated from message shw.AddFamilyMemberRequest
 */
export class AddFamilyMemberRequest extends Message<AddFamilyMemberRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: uint64 familyId = 3;
   */
  familyId = protoInt64.zero;

  constructor(data?: PartialMessage<AddFamilyMemberRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.AddFamilyMemberRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddFamilyMemberRequest {
    return new AddFamilyMemberRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddFamilyMemberRequest {
    return new AddFamilyMemberRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddFamilyMemberRequest {
    return new AddFamilyMemberRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddFamilyMemberRequest | PlainMessage<AddFamilyMemberRequest> | undefined, b: AddFamilyMemberRequest | PlainMessage<AddFamilyMemberRequest> | undefined): boolean {
    return proto3.util.equals(AddFamilyMemberRequest, a, b);
  }
}

/**
 * @generated from message shw.FamilyResponse
 */
export class FamilyResponse extends Message<FamilyResponse> {
  /**
   * @generated from field: shw.Family family = 1;
   */
  family?: Family;

  constructor(data?: PartialMessage<FamilyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "family", kind: "message", T: Family },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyResponse {
    return new FamilyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyResponse {
    return new FamilyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyResponse {
    return new FamilyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyResponse | PlainMessage<FamilyResponse> | undefined, b: FamilyResponse | PlainMessage<FamilyResponse> | undefined): boolean {
    return proto3.util.equals(FamilyResponse, a, b);
  }
}

/**
 * @generated from message shw.Family
 */
export class Family extends Message<Family> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: repeated shw.UserInfo user = 2;
   */
  user: UserInfo[] = [];

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string pointPerWorkTime = 4;
   */
  pointPerWorkTime = "";

  constructor(data?: PartialMessage<Family>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.Family";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "user", kind: "message", T: UserInfo, repeated: true },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "pointPerWorkTime", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Family {
    return new Family().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Family {
    return new Family().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Family {
    return new Family().fromJsonString(jsonString, options);
  }

  static equals(a: Family | PlainMessage<Family> | undefined, b: Family | PlainMessage<Family> | undefined): boolean {
    return proto3.util.equals(Family, a, b);
  }
}

