// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts,import_extension=none"
// @generated from file housework.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Housework, HouseworkDetailRequest, HouseworkDetailResponse, HouseworkMemo, HouseworkMemoRequest, HouseworkMemoResponse, HouseworkPointHistoryRequest, HouseworkPointHistoryResponse, HouseworkPointRequest, HouseworkPointResponse, HouseworkRequest, HouseworkResponse, HouseworkSchedule, HouseworkScheduleRequest, HouseworkScheduleResponse, HouseworkSchedulesRequest, HouseworkSchedulesResponse, HouseworkTargetRequest, HouseworkTemplate, HouseworkTemplateRequest, HouseworkTemplateResponse, HouseworkTemplatesRequest, HouseworkTemplatesResponse } from "./housework_pb";
import { MethodKind } from "@bufbuild/protobuf";
import { CommonResponse } from "./common_pb";

/**
 * @generated from service shw.HouseworkService
 */
export const HouseworkService = {
  typeName: "shw.HouseworkService",
  methods: {
    /**
     * @generated from rpc shw.HouseworkService.GetHousework
     */
    getHousework: {
      name: "GetHousework",
      I: HouseworkRequest,
      O: HouseworkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.GetHouseworkDetail
     */
    getHouseworkDetail: {
      name: "GetHouseworkDetail",
      I: HouseworkDetailRequest,
      O: HouseworkDetailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.CreateHousework
     */
    createHousework: {
      name: "CreateHousework",
      I: Housework,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.UpdateHousework
     */
    updateHousework: {
      name: "UpdateHousework",
      I: Housework,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.FinishHousework
     */
    finishHousework: {
      name: "FinishHousework",
      I: HouseworkTargetRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.DeleteHousework
     */
    deleteHousework: {
      name: "DeleteHousework",
      I: HouseworkTargetRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service shw.HouseworkMemoService
 */
export const HouseworkMemoService = {
  typeName: "shw.HouseworkMemoService",
  methods: {
    /**
     * @generated from rpc shw.HouseworkMemoService.GetHouseworkMemo
     */
    getHouseworkMemo: {
      name: "GetHouseworkMemo",
      I: HouseworkMemoRequest,
      O: HouseworkMemoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkMemoService.CreateHouseworkMemo
     */
    createHouseworkMemo: {
      name: "CreateHouseworkMemo",
      I: HouseworkMemo,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkMemoService.UpdateHouseworkMemo
     */
    updateHouseworkMemo: {
      name: "UpdateHouseworkMemo",
      I: HouseworkMemo,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkMemoService.DeleteHouseworkMemo
     */
    deleteHouseworkMemo: {
      name: "DeleteHouseworkMemo",
      I: HouseworkMemo,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service shw.HouseworkPointService
 */
export const HouseworkPointService = {
  typeName: "shw.HouseworkPointService",
  methods: {
    /**
     * @generated from rpc shw.HouseworkPointService.GetHouseworkPoint
     */
    getHouseworkPoint: {
      name: "GetHouseworkPoint",
      I: HouseworkPointRequest,
      O: HouseworkPointResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkPointService.GetHouseworkPointHistory
     */
    getHouseworkPointHistory: {
      name: "GetHouseworkPointHistory",
      I: HouseworkPointHistoryRequest,
      O: HouseworkPointHistoryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service shw.HouseworkTemplateService
 */
export const HouseworkTemplateService = {
  typeName: "shw.HouseworkTemplateService",
  methods: {
    /**
     * @generated from rpc shw.HouseworkTemplateService.GetHouseworkTemplate
     */
    getHouseworkTemplate: {
      name: "GetHouseworkTemplate",
      I: HouseworkTemplateRequest,
      O: HouseworkTemplateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkTemplateService.GetHouseworkTemplates
     */
    getHouseworkTemplates: {
      name: "GetHouseworkTemplates",
      I: HouseworkTemplatesRequest,
      O: HouseworkTemplatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkTemplateService.CreateHouseworkTemplate
     */
    createHouseworkTemplate: {
      name: "CreateHouseworkTemplate",
      I: HouseworkTemplate,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkTemplateService.UpdateHouseworkTemplate
     */
    updateHouseworkTemplate: {
      name: "UpdateHouseworkTemplate",
      I: HouseworkTemplate,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkTemplateService.DeleteHouseworkTemplate
     */
    deleteHouseworkTemplate: {
      name: "DeleteHouseworkTemplate",
      I: HouseworkTemplate,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service shw.HouseworkScheduleService
 */
export const HouseworkScheduleService = {
  typeName: "shw.HouseworkScheduleService",
  methods: {
    /**
     * @generated from rpc shw.HouseworkScheduleService.GetHouseworkSchedules
     */
    getHouseworkSchedules: {
      name: "GetHouseworkSchedules",
      I: HouseworkSchedulesRequest,
      O: HouseworkSchedulesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkScheduleService.GetHouseworkSchedule
     */
    getHouseworkSchedule: {
      name: "GetHouseworkSchedule",
      I: HouseworkScheduleRequest,
      O: HouseworkScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkScheduleService.CreateHouseworkSchedule
     */
    createHouseworkSchedule: {
      name: "CreateHouseworkSchedule",
      I: HouseworkSchedule,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkScheduleService.UpdateHouseworkSchedule
     */
    updateHouseworkSchedule: {
      name: "UpdateHouseworkSchedule",
      I: HouseworkSchedule,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkScheduleService.DeleteHouseworkSchedule
     */
    deleteHouseworkSchedule: {
      name: "DeleteHouseworkSchedule",
      I: HouseworkScheduleRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

