// @generated by protoc-gen-es v1.7.2 with parameter "target=ts,import_extension=none"
// @generated from file housework.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { UserInfo } from "./common_pb";

/**
 * @generated from message shw.HouseworkRequest
 */
export class HouseworkRequest extends Message<HouseworkRequest> {
  /**
   * @generated from field: uint64 familyId = 1;
   */
  familyId = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkRequest {
    return new HouseworkRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkRequest {
    return new HouseworkRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkRequest {
    return new HouseworkRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkRequest | PlainMessage<HouseworkRequest> | undefined, b: HouseworkRequest | PlainMessage<HouseworkRequest> | undefined): boolean {
    return proto3.util.equals(HouseworkRequest, a, b);
  }
}

/**
 * @generated from message shw.HouseworkDetailRequest
 */
export class HouseworkDetailRequest extends Message<HouseworkDetailRequest> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkDetailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkDetailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkDetailRequest {
    return new HouseworkDetailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkDetailRequest {
    return new HouseworkDetailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkDetailRequest {
    return new HouseworkDetailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkDetailRequest | PlainMessage<HouseworkDetailRequest> | undefined, b: HouseworkDetailRequest | PlainMessage<HouseworkDetailRequest> | undefined): boolean {
    return proto3.util.equals(HouseworkDetailRequest, a, b);
  }
}

/**
 * @generated from message shw.HouseworkMemoRequest
 */
export class HouseworkMemoRequest extends Message<HouseworkMemoRequest> {
  /**
   * @generated from field: uint64 houseworkId = 1;
   */
  houseworkId = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkMemoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkMemoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "houseworkId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkMemoRequest {
    return new HouseworkMemoRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkMemoRequest {
    return new HouseworkMemoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkMemoRequest {
    return new HouseworkMemoRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkMemoRequest | PlainMessage<HouseworkMemoRequest> | undefined, b: HouseworkMemoRequest | PlainMessage<HouseworkMemoRequest> | undefined): boolean {
    return proto3.util.equals(HouseworkMemoRequest, a, b);
  }
}

/**
 * @generated from message shw.HouseworkPointRequest
 */
export class HouseworkPointRequest extends Message<HouseworkPointRequest> {
  /**
   * @generated from field: uint64 userId = 1;
   */
  userId = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkPointRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkPointRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkPointRequest {
    return new HouseworkPointRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkPointRequest {
    return new HouseworkPointRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkPointRequest {
    return new HouseworkPointRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkPointRequest | PlainMessage<HouseworkPointRequest> | undefined, b: HouseworkPointRequest | PlainMessage<HouseworkPointRequest> | undefined): boolean {
    return proto3.util.equals(HouseworkPointRequest, a, b);
  }
}

/**
 * @generated from message shw.HouseworkTemplateRequest
 */
export class HouseworkTemplateRequest extends Message<HouseworkTemplateRequest> {
  /**
   * @generated from field: uint64 familyId = 1;
   */
  familyId = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkTemplateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkTemplateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkTemplateRequest {
    return new HouseworkTemplateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkTemplateRequest {
    return new HouseworkTemplateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkTemplateRequest {
    return new HouseworkTemplateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkTemplateRequest | PlainMessage<HouseworkTemplateRequest> | undefined, b: HouseworkTemplateRequest | PlainMessage<HouseworkTemplateRequest> | undefined): boolean {
    return proto3.util.equals(HouseworkTemplateRequest, a, b);
  }
}

/**
 * @generated from message shw.HouseworkPointHistoryRequest
 */
export class HouseworkPointHistoryRequest extends Message<HouseworkPointHistoryRequest> {
  /**
   * @generated from field: uint64 userId = 1;
   */
  userId = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkPointHistoryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkPointHistoryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkPointHistoryRequest {
    return new HouseworkPointHistoryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkPointHistoryRequest {
    return new HouseworkPointHistoryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkPointHistoryRequest {
    return new HouseworkPointHistoryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkPointHistoryRequest | PlainMessage<HouseworkPointHistoryRequest> | undefined, b: HouseworkPointHistoryRequest | PlainMessage<HouseworkPointHistoryRequest> | undefined): boolean {
    return proto3.util.equals(HouseworkPointHistoryRequest, a, b);
  }
}

/**
 * @generated from message shw.HouseworkResponse
 */
export class HouseworkResponse extends Message<HouseworkResponse> {
  /**
   * @generated from field: repeated shw.Housework housework = 1;
   */
  housework: Housework[] = [];

  constructor(data?: PartialMessage<HouseworkResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "housework", kind: "message", T: Housework, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkResponse {
    return new HouseworkResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkResponse {
    return new HouseworkResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkResponse {
    return new HouseworkResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkResponse | PlainMessage<HouseworkResponse> | undefined, b: HouseworkResponse | PlainMessage<HouseworkResponse> | undefined): boolean {
    return proto3.util.equals(HouseworkResponse, a, b);
  }
}

/**
 * @generated from message shw.HouseworkDetailResponse
 */
export class HouseworkDetailResponse extends Message<HouseworkDetailResponse> {
  /**
   * @generated from field: shw.Housework housework = 1;
   */
  housework?: Housework;

  /**
   * @generated from field: repeated shw.HouseworkMemo memo = 2;
   */
  memo: HouseworkMemo[] = [];

  constructor(data?: PartialMessage<HouseworkDetailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkDetailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "housework", kind: "message", T: Housework },
    { no: 2, name: "memo", kind: "message", T: HouseworkMemo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkDetailResponse {
    return new HouseworkDetailResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkDetailResponse {
    return new HouseworkDetailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkDetailResponse {
    return new HouseworkDetailResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkDetailResponse | PlainMessage<HouseworkDetailResponse> | undefined, b: HouseworkDetailResponse | PlainMessage<HouseworkDetailResponse> | undefined): boolean {
    return proto3.util.equals(HouseworkDetailResponse, a, b);
  }
}

/**
 * @generated from message shw.HouseworkMemoResponse
 */
export class HouseworkMemoResponse extends Message<HouseworkMemoResponse> {
  /**
   * @generated from field: repeated shw.HouseworkMemo memo = 1;
   */
  memo: HouseworkMemo[] = [];

  constructor(data?: PartialMessage<HouseworkMemoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkMemoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "memo", kind: "message", T: HouseworkMemo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkMemoResponse {
    return new HouseworkMemoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkMemoResponse {
    return new HouseworkMemoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkMemoResponse {
    return new HouseworkMemoResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkMemoResponse | PlainMessage<HouseworkMemoResponse> | undefined, b: HouseworkMemoResponse | PlainMessage<HouseworkMemoResponse> | undefined): boolean {
    return proto3.util.equals(HouseworkMemoResponse, a, b);
  }
}

/**
 * @generated from message shw.HouseworkPointResponse
 */
export class HouseworkPointResponse extends Message<HouseworkPointResponse> {
  /**
   * @generated from field: shw.HouseworkPoint point = 1;
   */
  point?: HouseworkPoint;

  constructor(data?: PartialMessage<HouseworkPointResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkPointResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "point", kind: "message", T: HouseworkPoint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkPointResponse {
    return new HouseworkPointResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkPointResponse {
    return new HouseworkPointResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkPointResponse {
    return new HouseworkPointResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkPointResponse | PlainMessage<HouseworkPointResponse> | undefined, b: HouseworkPointResponse | PlainMessage<HouseworkPointResponse> | undefined): boolean {
    return proto3.util.equals(HouseworkPointResponse, a, b);
  }
}

/**
 * @generated from message shw.HouseworkPointHistoryResponse
 */
export class HouseworkPointHistoryResponse extends Message<HouseworkPointHistoryResponse> {
  /**
   * @generated from field: repeated shw.HouseworkPointHistory history = 1;
   */
  history: HouseworkPointHistory[] = [];

  constructor(data?: PartialMessage<HouseworkPointHistoryResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkPointHistoryResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "history", kind: "message", T: HouseworkPointHistory, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkPointHistoryResponse {
    return new HouseworkPointHistoryResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkPointHistoryResponse {
    return new HouseworkPointHistoryResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkPointHistoryResponse {
    return new HouseworkPointHistoryResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkPointHistoryResponse | PlainMessage<HouseworkPointHistoryResponse> | undefined, b: HouseworkPointHistoryResponse | PlainMessage<HouseworkPointHistoryResponse> | undefined): boolean {
    return proto3.util.equals(HouseworkPointHistoryResponse, a, b);
  }
}

/**
 * @generated from message shw.HouseworkTemplateResponse
 */
export class HouseworkTemplateResponse extends Message<HouseworkTemplateResponse> {
  /**
   * @generated from field: repeated shw.HouseworkTemplate template = 1;
   */
  template: HouseworkTemplate[] = [];

  constructor(data?: PartialMessage<HouseworkTemplateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkTemplateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "template", kind: "message", T: HouseworkTemplate, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkTemplateResponse {
    return new HouseworkTemplateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkTemplateResponse {
    return new HouseworkTemplateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkTemplateResponse {
    return new HouseworkTemplateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkTemplateResponse | PlainMessage<HouseworkTemplateResponse> | undefined, b: HouseworkTemplateResponse | PlainMessage<HouseworkTemplateResponse> | undefined): boolean {
    return proto3.util.equals(HouseworkTemplateResponse, a, b);
  }
}

/**
 * @generated from message shw.Housework
 */
export class Housework extends Message<Housework> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: uint64 familyId = 2;
   */
  familyId = protoInt64.zero;

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string detail = 4;
   */
  detail = "";

  /**
   * @generated from field: string status = 5;
   */
  status = "";

  /**
   * @generated from field: shw.UserInfo workUser = 6;
   */
  workUser?: UserInfo;

  /**
   * @generated from field: int64 startedAt = 7;
   */
  startedAt = protoInt64.zero;

  /**
   * @generated from field: int64 endedAt = 8;
   */
  endedAt = protoInt64.zero;

  constructor(data?: PartialMessage<Housework>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.Housework";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "workUser", kind: "message", T: UserInfo },
    { no: 7, name: "startedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "endedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Housework {
    return new Housework().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Housework {
    return new Housework().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Housework {
    return new Housework().fromJsonString(jsonString, options);
  }

  static equals(a: Housework | PlainMessage<Housework> | undefined, b: Housework | PlainMessage<Housework> | undefined): boolean {
    return proto3.util.equals(Housework, a, b);
  }
}

/**
 * @generated from message shw.HouseworkMemo
 */
export class HouseworkMemo extends Message<HouseworkMemo> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: uint64 houseworkId = 2;
   */
  houseworkId = protoInt64.zero;

  /**
   * @generated from field: string text = 3;
   */
  text = "";

  /**
   * @generated from field: shw.UserInfo draftUser = 4;
   */
  draftUser?: UserInfo;

  /**
   * @generated from field: int64 createdAt = 5;
   */
  createdAt = protoInt64.zero;

  /**
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkMemo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkMemo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "houseworkId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "draftUser", kind: "message", T: UserInfo },
    { no: 5, name: "createdAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "updatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkMemo {
    return new HouseworkMemo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkMemo {
    return new HouseworkMemo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkMemo {
    return new HouseworkMemo().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkMemo | PlainMessage<HouseworkMemo> | undefined, b: HouseworkMemo | PlainMessage<HouseworkMemo> | undefined): boolean {
    return proto3.util.equals(HouseworkMemo, a, b);
  }
}

/**
 * @generated from message shw.HouseworkPoint
 */
export class HouseworkPoint extends Message<HouseworkPoint> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: shw.UserInfo user = 2;
   */
  user?: UserInfo;

  /**
   * @generated from field: int64 point = 4;
   */
  point = protoInt64.zero;

  /**
   * @generated from field: int64 createdAt = 5;
   */
  createdAt = protoInt64.zero;

  /**
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkPoint>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkPoint";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "user", kind: "message", T: UserInfo },
    { no: 4, name: "point", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "createdAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "updatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkPoint {
    return new HouseworkPoint().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkPoint {
    return new HouseworkPoint().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkPoint {
    return new HouseworkPoint().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkPoint | PlainMessage<HouseworkPoint> | undefined, b: HouseworkPoint | PlainMessage<HouseworkPoint> | undefined): boolean {
    return proto3.util.equals(HouseworkPoint, a, b);
  }
}

/**
 * @generated from message shw.HouseworkPointHistory
 */
export class HouseworkPointHistory extends Message<HouseworkPointHistory> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: shw.UserInfo user = 2;
   */
  user?: UserInfo;

  /**
   * @generated from field: string detail = 3;
   */
  detail = "";

  /**
   * @generated from field: int64 point = 4;
   */
  point = protoInt64.zero;

  /**
   * @generated from field: int64 createdAt = 5;
   */
  createdAt = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkPointHistory>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkPointHistory";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "user", kind: "message", T: UserInfo },
    { no: 3, name: "detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "point", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "createdAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkPointHistory {
    return new HouseworkPointHistory().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkPointHistory {
    return new HouseworkPointHistory().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkPointHistory {
    return new HouseworkPointHistory().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkPointHistory | PlainMessage<HouseworkPointHistory> | undefined, b: HouseworkPointHistory | PlainMessage<HouseworkPointHistory> | undefined): boolean {
    return proto3.util.equals(HouseworkPointHistory, a, b);
  }
}

/**
 * @generated from message shw.HouseworkTemplate
 */
export class HouseworkTemplate extends Message<HouseworkTemplate> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: uint64 familyId = 2;
   */
  familyId = protoInt64.zero;

  /**
   * @generated from field: string name = 3;
   */
  name = "";

  /**
   * @generated from field: string detail = 4;
   */
  detail = "";

  /**
   * @generated from field: int64 createdAt = 5;
   */
  createdAt = protoInt64.zero;

  /**
   * @generated from field: int64 updatedAt = 6;
   */
  updatedAt = protoInt64.zero;

  constructor(data?: PartialMessage<HouseworkTemplate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.HouseworkTemplate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "familyId", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "detail", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "createdAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "updatedAt", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HouseworkTemplate {
    return new HouseworkTemplate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HouseworkTemplate {
    return new HouseworkTemplate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HouseworkTemplate {
    return new HouseworkTemplate().fromJsonString(jsonString, options);
  }

  static equals(a: HouseworkTemplate | PlainMessage<HouseworkTemplate> | undefined, b: HouseworkTemplate | PlainMessage<HouseworkTemplate> | undefined): boolean {
    return proto3.util.equals(HouseworkTemplate, a, b);
  }
}

