// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file housework.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Housework, HouseworkDetailRequest, HouseworkDetailResponse, HouseworkMemo, HouseworkMemoRequest, HouseworkMemoResponse, HouseworkPointHistoryRequest, HouseworkPointHistoryResponse, HouseworkPointRequest, HouseworkPointResponse, HouseworkRequest, HouseworkResponse } from "./housework_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { CommonResponse } from "./common_pb.js";

/**
 * @generated from service shw.HouseworkService
 */
export const HouseworkService = {
  typeName: "shw.HouseworkService",
  methods: {
    /**
     * @generated from rpc shw.HouseworkService.GetHousework
     */
    getHousework: {
      name: "GetHousework",
      I: HouseworkRequest,
      O: HouseworkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.GetHouseworkDetail
     */
    getHouseworkDetail: {
      name: "GetHouseworkDetail",
      I: HouseworkDetailRequest,
      O: HouseworkDetailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.CreateHousework
     */
    createHousework: {
      name: "CreateHousework",
      I: Housework,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.UpdateHousework
     */
    updateHousework: {
      name: "UpdateHousework",
      I: Housework,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.FinishHousework
     */
    finishHousework: {
      name: "FinishHousework",
      I: Housework,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.DeleteHousework
     */
    deleteHousework: {
      name: "DeleteHousework",
      I: Housework,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.GetHouseworkMemo
     */
    getHouseworkMemo: {
      name: "GetHouseworkMemo",
      I: HouseworkMemoRequest,
      O: HouseworkMemoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.CreateHouseworkMemo
     */
    createHouseworkMemo: {
      name: "CreateHouseworkMemo",
      I: HouseworkMemo,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.UpdateHouseworkMemo
     */
    updateHouseworkMemo: {
      name: "UpdateHouseworkMemo",
      I: HouseworkMemo,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.DeleteHouseworkMemo
     */
    deleteHouseworkMemo: {
      name: "DeleteHouseworkMemo",
      I: HouseworkMemo,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.GetHouseworkPoint
     */
    getHouseworkPoint: {
      name: "GetHouseworkPoint",
      I: HouseworkPointRequest,
      O: HouseworkPointResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.HouseworkService.GetHouseworkPointHistory
     */
    getHouseworkPointHistory: {
      name: "GetHouseworkPointHistory",
      I: HouseworkPointHistoryRequest,
      O: HouseworkPointHistoryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

