// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file point.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FamilyPointList, FamilyPointListRequest, Point, PointRequest, PointResponse } from "./point_pb";
import { MethodKind } from "@bufbuild/protobuf";
import { CommonResponse } from "./common_pb";

/**
 * @generated from service shw.PointService
 */
export const PointService = {
  typeName: "shw.PointService",
  methods: {
    /**
     * @generated from rpc shw.PointService.GetPoint
     */
    getPoint: {
      name: "GetPoint",
      I: PointRequest,
      O: PointResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.PointService.GetFamilyPointList
     */
    getFamilyPointList: {
      name: "GetFamilyPointList",
      I: FamilyPointListRequest,
      O: FamilyPointList,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.PointService.CreatePoint
     */
    createPoint: {
      name: "CreatePoint",
      I: Point,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.PointService.UpdatePoint
     */
    updatePoint: {
      name: "UpdatePoint",
      I: Point,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.PointService.DeletePoint
     */
    deletePoint: {
      name: "DeletePoint",
      I: Point,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

