// @generated by protoc-gen-es v1.8.0 with parameter "target=ts,import_extension=none"
// @generated from file point.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message shw.Point
 */
export class Point extends Message<Point> {
  /**
   * @generated from field: string userId = 1;
   */
  userId = "";

  /**
   * @generated from field: int64 point = 2;
   */
  point = protoInt64.zero;

  constructor(data?: PartialMessage<Point>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.Point";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "point", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Point {
    return new Point().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Point {
    return new Point().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Point {
    return new Point().fromJsonString(jsonString, options);
  }

  static equals(a: Point | PlainMessage<Point> | undefined, b: Point | PlainMessage<Point> | undefined): boolean {
    return proto3.util.equals(Point, a, b);
  }
}

/**
 * @generated from message shw.PointRequest
 */
export class PointRequest extends Message<PointRequest> {
  /**
   * @generated from field: string userId = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<PointRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.PointRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PointRequest {
    return new PointRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PointRequest {
    return new PointRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PointRequest {
    return new PointRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PointRequest | PlainMessage<PointRequest> | undefined, b: PointRequest | PlainMessage<PointRequest> | undefined): boolean {
    return proto3.util.equals(PointRequest, a, b);
  }
}

/**
 * @generated from message shw.PointResponse
 */
export class PointResponse extends Message<PointResponse> {
  /**
   * @generated from field: shw.Point point = 1;
   */
  point?: Point;

  constructor(data?: PartialMessage<PointResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.PointResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "point", kind: "message", T: Point },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PointResponse {
    return new PointResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PointResponse {
    return new PointResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PointResponse {
    return new PointResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PointResponse | PlainMessage<PointResponse> | undefined, b: PointResponse | PlainMessage<PointResponse> | undefined): boolean {
    return proto3.util.equals(PointResponse, a, b);
  }
}

/**
 * @generated from message shw.FamilyPointListRequest
 */
export class FamilyPointListRequest extends Message<FamilyPointListRequest> {
  /**
   * @generated from field: string familyId = 1;
   */
  familyId = "";

  constructor(data?: PartialMessage<FamilyPointListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyPointListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "familyId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyPointListRequest {
    return new FamilyPointListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyPointListRequest {
    return new FamilyPointListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyPointListRequest {
    return new FamilyPointListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyPointListRequest | PlainMessage<FamilyPointListRequest> | undefined, b: FamilyPointListRequest | PlainMessage<FamilyPointListRequest> | undefined): boolean {
    return proto3.util.equals(FamilyPointListRequest, a, b);
  }
}

/**
 * @generated from message shw.FamilyPointList
 */
export class FamilyPointList extends Message<FamilyPointList> {
  /**
   * @generated from field: repeated shw.Point points = 1;
   */
  points: Point[] = [];

  constructor(data?: PartialMessage<FamilyPointList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shw.FamilyPointList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "points", kind: "message", T: Point, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FamilyPointList {
    return new FamilyPointList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FamilyPointList {
    return new FamilyPointList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FamilyPointList {
    return new FamilyPointList().fromJsonString(jsonString, options);
  }

  static equals(a: FamilyPointList | PlainMessage<FamilyPointList> | undefined, b: FamilyPointList | PlainMessage<FamilyPointList> | undefined): boolean {
    return proto3.util.equals(FamilyPointList, a, b);
  }
}

