// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file sample.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HelloRequest, HelloResponse } from "./sample_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service shw.HelloService
 */
export const HelloService = {
  typeName: "shw.HelloService",
  methods: {
    /**
     * @generated from rpc shw.HelloService.Hello
     */
    hello: {
      name: "Hello",
      I: HelloRequest,
      O: HelloResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

