// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file sample.proto (package shw, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sample.proto.
 */
export const file_sample: GenFile = /*@__PURE__*/
  fileDesc("CgxzYW1wbGUucHJvdG8SA3NodyIcCgxIZWxsb1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIgCg1IZWxsb1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkyQAoMSGVsbG9TZXJ2aWNlEjAKBUhlbGxvEhEuc2h3LkhlbGxvUmVxdWVzdBoSLnNody5IZWxsb1Jlc3BvbnNlIgBCEloQc2h3Z3JwYy9wa2cvZ3JwY2IGcHJvdG8z");

/**
 * @generated from message shw.HelloRequest
 */
export type HelloRequest = Message<"shw.HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message shw.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_sample, 0);

/**
 * @generated from message shw.HelloResponse
 */
export type HelloResponse = Message<"shw.HelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message shw.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export const HelloResponseSchema: GenMessage<HelloResponse> = /*@__PURE__*/
  messageDesc(file_sample, 1);

/**
 * @generated from service shw.HelloService
 */
export const HelloService: GenService<{
  /**
   * @generated from rpc shw.HelloService.Hello
   */
  hello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sample, 0);

