// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file user.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBelongToUserRequest, GetBelongToUserResponse, UpdateRoleRequest } from "./user_pb";
import { CommonResponse } from "./common_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service shw.UserService
 */
export const UserService = {
  typeName: "shw.UserService",
  methods: {
    /**
     * @generated from rpc shw.UserService.UpdateRole
     */
    updateRole: {
      name: "UpdateRole",
      I: UpdateRoleRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shw.UserService.GetBelongToUser
     */
    getBelongToUser: {
      name: "GetBelongToUser",
      I: GetBelongToUserRequest,
      O: GetBelongToUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

