// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file user.proto (package shw, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { CommonResponseSchema } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvEgNzaHciQgoEVXNlchIKCgJpZBgBIAEoBBIMCgRuYW1lGAIgASgJEg4KBnJvbGVJZBgDIAEoBBIQCghmYW1pbHlJZBgEIAEoBCIzChFVcGRhdGVSb2xlUmVxdWVzdBIOCgZ1c2VySWQYASABKAQSDgoGcm9sZUlkGAIgASgEIioKFkdldEJlbG9uZ1RvVXNlclJlcXVlc3QSEAoIZmFtaWx5SWQYASABKAQiMwoXR2V0QmVsb25nVG9Vc2VyUmVzcG9uc2USGAoFdXNlcnMYASADKAsyCS5zaHcuVXNlcjKaAQoLVXNlclNlcnZpY2USOwoKVXBkYXRlUm9sZRIWLnNody5VcGRhdGVSb2xlUmVxdWVzdBoTLnNody5Db21tb25SZXNwb25zZSIAEk4KD0dldEJlbG9uZ1RvVXNlchIbLnNody5HZXRCZWxvbmdUb1VzZXJSZXF1ZXN0Ghwuc2h3LkdldEJlbG9uZ1RvVXNlclJlc3BvbnNlIgBCEloQc2h3Z3JwYy9wa2cvZ3JwY2IGcHJvdG8z", [file_common]);

/**
 * @generated from message shw.User
 */
export type User = Message<"shw.User"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: uint64 roleId = 3;
   */
  roleId: bigint;

  /**
   * @generated from field: uint64 familyId = 4;
   */
  familyId: bigint;
};

/**
 * Describes the message shw.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * @generated from message shw.UpdateRoleRequest
 */
export type UpdateRoleRequest = Message<"shw.UpdateRoleRequest"> & {
  /**
   * @generated from field: uint64 userId = 1;
   */
  userId: bigint;

  /**
   * @generated from field: uint64 roleId = 2;
   */
  roleId: bigint;
};

/**
 * Describes the message shw.UpdateRoleRequest.
 * Use `create(UpdateRoleRequestSchema)` to create a new message.
 */
export const UpdateRoleRequestSchema: GenMessage<UpdateRoleRequest> = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * @generated from message shw.GetBelongToUserRequest
 */
export type GetBelongToUserRequest = Message<"shw.GetBelongToUserRequest"> & {
  /**
   * @generated from field: uint64 familyId = 1;
   */
  familyId: bigint;
};

/**
 * Describes the message shw.GetBelongToUserRequest.
 * Use `create(GetBelongToUserRequestSchema)` to create a new message.
 */
export const GetBelongToUserRequestSchema: GenMessage<GetBelongToUserRequest> = /*@__PURE__*/
  messageDesc(file_user, 2);

/**
 * @generated from message shw.GetBelongToUserResponse
 */
export type GetBelongToUserResponse = Message<"shw.GetBelongToUserResponse"> & {
  /**
   * @generated from field: repeated shw.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message shw.GetBelongToUserResponse.
 * Use `create(GetBelongToUserResponseSchema)` to create a new message.
 */
export const GetBelongToUserResponseSchema: GenMessage<GetBelongToUserResponse> = /*@__PURE__*/
  messageDesc(file_user, 3);

/**
 * @generated from service shw.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc shw.UserService.UpdateRole
   */
  updateRole: {
    methodKind: "unary";
    input: typeof UpdateRoleRequestSchema;
    output: typeof CommonResponseSchema;
  },
  /**
   * @generated from rpc shw.UserService.GetBelongToUser
   */
  getBelongToUser: {
    methodKind: "unary";
    input: typeof GetBelongToUserRequestSchema;
    output: typeof GetBelongToUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user, 0);

