// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file user.proto (package shw, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { UpdateRoleRequest } from "./user_pb.js";
import { CommonResponse } from "./common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service shw.UserService
 */
export const UserService = {
  typeName: "shw.UserService",
  methods: {
    /**
     * @generated from rpc shw.UserService.UpdateRole
     */
    updateRole: {
      name: "UpdateRole",
      I: UpdateRoleRequest,
      O: CommonResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

