import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Auth0Provider } from '@auth0/nextjs-auth0/client';
import Header from "@/components/common/Header";
import "@/styles/common.css"
import CommonInfoProvider from "@/context/CommonContext";
import ThemeProviderWrapper from "@/components/common/ThemeProviderWrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-basic-200`}>
        <ThemeProviderWrapper>
          <Auth0Provider>
            <CommonInfoProvider familyId={'1'}>
              <Header />
              <main className="flex min-h-screen flex-col items-center justify-between bg-basic-200 pl-8">
                {children}
              </main>
            </CommonInfoProvider>
          </Auth0Provider>
        </ThemeProviderWrapper>
      </body>
    </html>
  )
}
