import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Header from "@/components/common/Header";
import "@/styles/common.scss"
import CommonInfoProvider from "@/context/CommonContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <CommonInfoProvider familyId={'1'}>
          <body className={`${inter.className} bg-base-200`}>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between bg-base-200 pl-8">
            {children}
          </main>
          </body>
        </CommonInfoProvider>
      </UserProvider>
    </html>
  )
}
